[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Increase max body size to 100MB
[functions]
  included_files = ["dist/**/*"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https: wss:;"

[dev]
  targetPort = 5173
  port = 8888
  framework = "vite"
  autoLaunch = true
  command = "npm run dev"

# Increase max body size to 100MB
[[plugins]]
  package = "@netlify/plugin-functions-core"

  [plugins.inputs]
    maxPayloadSize = "100mb"