[build]
  command = "CI=false npm run build"
  publish = "dist"
  environment = { SKIP_PREFLIGHT_CHECK = "true", TSC_COMPILE_ON_ERROR = "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  framework = "vite"
  autoLaunch = true